version: '3.8'

services:
  specialization_week_rag:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./app:/usr/src/app
      - ./app/requirements.txt:/usr/src/app/requirements.txt
